In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LogisticRegression
from sklearn.model_selection import train_test_split as tts, GridSearchCV
from sklearn.metrics import mean_absolute_error as MAE, r2_score as R2
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
df = pd.read_csv('Test_Data_Full.csv')

In [54]:
X = df[['day',
 'unique_carrier_rank',
 'tail_num_rank',
 'origin_rank',
 'dest_rank',
 'distance',
 'crs_arr_time',
 'crs_elapsed_time',
 'sdomt_gallons',
 'tdomt_gallons',
 'ts_cost',
 'tdomt_cost']]

df = df[['day',
 'unique_carrier_rank',
 'tail_num_rank',
 'origin_rank',
 'dest_rank',
 'distance',
 'crs_arr_time',
 'crs_elapsed_time',
 'sdomt_gallons',
 'tdomt_gallons',
 'ts_cost',
 'tdomt_cost']]

In [4]:
model = pickle.load(open('final_ridge_regression_model.sav','rb'))

In [5]:
scaler = pickle.load(open('scaler_model.sav','rb'))

In [55]:
X = scaler.transform(X)

In [56]:
target = model.predict(X)

In [57]:
df['predicted_delay'] = target

In [58]:
df

,day,unique_carrier_rank,tail_num_rank,origin_rank,dest_rank,distance,crs_arr_time,crs_elapsed_time,sdomt_gallons,tdomt_gallons,ts_cost,tdomt_cost,predicted_delay
0,1,9,612.0,63.0,157.0,262,1812,72,173505482.0,174171571.0,558826129,338396257,945.972951
1,1,9,4849.0,241.0,198.0,813,910,130,173505482.0,174171571.0,558826129,338396257,503.093011
2,1,3,2890.0,208.0,138.0,2343,2244,359,56426937.0,56468118.0,124581290,121153924,1198.933960
3,1,1,4079.0,115.0,82.0,255,1500,70,161138026.0,161332466.0,319313619,315397696,805.131557
4,1,8,2128.0,161.0,187.0,305,839,74,120128303.0,120886857.0,505600266,239129660,444.101605
...,...,...,...,...,...,...,...,...,...,...,...,...,...
85852,1,8,3823.0,142.0,201.0,955,2120,135,120128303.0,120886857.0,505600266,239129660,1141.638206
85853,1,9,4247.0,118.0,224.0,759,1709,130,173505482.0,174171571.0,558826129,338396257,920.880161
85854,1,10,5019.0,301.0,51.0,882,1123,143,13661026.0,14124731.0,30199307,31266501,617.431966
85855,1,8,940.0,221.0,118.0,488,1124,144,120128303.0,120886857.0,505600266,239129660,583.580957
85856,1,3,3918.0,96.0,63.0,417,753,98,56426937.0,56468118.0,124581290,121153924,405.708513

In [59]:
df.to_csv(path_or_buf = 'delay_predictions.csv', index = False)